/*data chi nhánh*/
insert into CHINHANH(TENCN,TRUONGCHINHANH)
VALUES ('TP. Hồ Chí Minh',null);
insert into CHINHANH(TENCN,TRUONGCHINHANH)
VALUES ('Đà Nẵng',null);
insert into CHINHANH(TENCN,TRUONGCHINHANH)
VALUES ('Hà Nội',null);
insert into CHINHANH(TENCN,TRUONGCHINHANH)
VALUES ('Hải Dương',null);
insert into CHINHANH(TENCN,TRUONGCHINHANH)
VALUES ('Huế',null);


/*data phòng ban*/
insert into PHONGBAN(TENPHONG,TRUONGPHONG,NGAYNHANCHUC,SONHANVIEN,CHINHANH)
VALUES ('Nhân Sự',null,TO_DATE('25/04/2017','DD/MM/YYYY'),10,1);
insert into PHONGBAN(TENPHONG,TRUONGPHONG,NGAYNHANCHUC,SONHANVIEN,CHINHANH)
VALUES ('Kế Toán',null,TO_DATE('25/03/2017','DD/MM/YYYY'),10,2);
insert into PHONGBAN(TENPHONG,TRUONGPHONG,NGAYNHANCHUC,SONHANVIEN,CHINHANH)
VALUES ('Kế Hoạch',null,TO_DATE('20/04/2017','DD/MM/YYYY'),10,3);
insert into PHONGBAN(TENPHONG,TRUONGPHONG,NGAYNHANCHUC,SONHANVIEN,CHINHANH)
VALUES ('Kinh Doanh',null,TO_DATE('5/04/2017','DD/MM/YYYY'),10,4);
insert into PHONGBAN(TENPHONG,TRUONGPHONG,NGAYNHANCHUC,SONHANVIEN,CHINHANH)
VALUES ('Kỹ Thuật',null,TO_DATE('2/04/2017','DD/MM/YYYY'),10,5);


/*data nhân viên*/
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Binsu','Hồ Chí Minh','123456789','NV01.lab01@gmail.com',1,1,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Bánh Tráng Trộn','Hồ Chí Minh','1123456789','NV02.lab01@gmail.com',1,1,550);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Susi Hàn Quốc','Hồ Chí Minh','1223456789','NV03.lab01@gmail.com',1,1,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Cánh Gà Chiên Mắm','Hà Nội','1233456789','NV04.lab01@gmail.com',1,1,600);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Hột Vịt Lộn','Hà Nội','1234456789','NV05.lab01@gmail.com',1,1,600);

insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Nguyễn Văn C','Hà Nội','1234556789','NV06.lab01@gmail.com',2,2,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Cao Mông D','Đà Nẵng','1234566789','NV07.lab01@gmail.com',2,2,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Si Mộng','Hồ Chí Minh','123456789','NV08.lab01@gmail.com',2,2,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Mộng Si','Hồ Chí Minh','1234567897','NV09.lab01@gmail.com',2,2,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Lùn Thế Kỷ','Hồ Chí Minh','1234556789','NV10.lab01@gmail.com',2,2,500);

insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Dương Quá','Hồ Chí Minh','1234567894','NV11.lab01@gmail.com',3,3,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Cô Long','Huế','1234567897','NV12.lab01@gmail.com',3,3,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Quách Tĩnh','Quãng Nam','1234556789','NV13.lab01@gmail.com',3,3,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Hoàng Dung','Quãng Ngãi','1234567894','NV14.lab01@gmail.com',3,3,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Lý Mạc Sầu','Hồ Chí Minh','1234556789','NV15.lab01@gmail.com',3,3,500);

insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Trần Trường Sinh','Hồ Chí Minh','1234567894','NV16.lab01@gmail.com',4,4,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Lặc Lạc','Huế','1234567897','NV17.lab01@gmail.com',4,4,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Từ Hữu Dung','Quãng Nam','1234556789','NV18.lab01@gmail.com',4,4,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Tam Thập Lục','Quãng Ngãi','1234567894','NV19.lab01@gmail.com',4,4,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Trang Hoán Vũ','Quãng Ngãi','1234567894','NV20.lab01@gmail.com',4,4,500);

insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Nguyễn Cao A','Hồ Chí Minh','1234567894','NV21.lab01@gmail.com',5,5,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Dương Thế B','Huế','1234567897','NV22.lab01@gmail.com',5,5,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Cao Bùi C','Quãng Nam','1234556789','NV23.lab01@gmail.com',5,5,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Dương Mịch','Quãng Ngãi','1234567894','NV24.lab01@gmail.com',5,5,500);
insert into NHANVIEN (HOTEN,DIACHI,DIENTHOAI,EMAIL,MAPHONG,CHINHANH,LUONG)
VALUES ('Cao Thâm','Quãng Ngãi','1234567894','NV25.lab01@gmail.com',5,5,500);

/*data dự án*/
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Bất động sản',1000000,1,03);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Xây Dựng',1000000,1,03);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Công nghệ sinh',2000000,2,08);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Dạy Học',2000000,2,08);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Trí tuệ',3000000,1,13);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Tự Động Hóa',3000000,1,13);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Autobot',4000000,1,18);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Bán Xe Máy',4000000,1,18);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Vật liệu rắn',5000000,1,23);
insert into DUAN(TENDA,KINHPHI,PHONGCHUTRI,TRUONGDA)
VALUES ('Thoát Nước',5000000,1,23);

/*data phân công*/
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (4,1,'Thành viên',20);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (4,2,'Giám sát',30);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (9,3,'Quản lý',40);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (9,4,'Thành viên',20);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (14,5,'Giám sát',30);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (14,6,'Quản lý',40);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (19,7,'Quản lý',40);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (19,8,'Thành viên',20);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (24,9,'Giám sát',30);
insert into PHANCONG (MANV,DUAN,VAITRO,PHUCAP)
VALUES (24,10,'Quản lý',40);

/*data chi tiêu*/
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí di chuyển',100,1);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí ăn uống',200,1);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí vật liệu',300,1);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí di chuyển',100,2);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí ăn uống',200,2);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí vật liệu',300,2);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí di chuyển',100,3);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí ăn uống',200,3);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí vật liệu',300,3);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí di chuyển',100,4);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí ăn uống',200,4);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí vật liệu',300,4);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí di chuyển',100,5);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí ăn uống',200,5);
insert into CHITIEU(TENCHITIEU,SOTIEN,DUAN)
VALUES ('Phí vật liệu',300,5);

update PHONGBAN set TRUONGPHONG=2 where MAPHONG=1;
update PHONGBAN set TRUONGPHONG=7 where MAPHONG=2;
update PHONGBAN set TRUONGPHONG=12 where MAPHONG=3;
update PHONGBAN set TRUONGPHONG=17 where MAPHONG=4;
update PHONGBAN set TRUONGPHONG=22 where MAPHONG=5;

update CHINHANH set TRUONGCHINHANH=1 where MACN=1;
update CHINHANH set TRUONGCHINHANH=6 where MACN=2;
update CHINHANH set TRUONGCHINHANH=11 where MACN=3;
update CHINHANH set TRUONGCHINHANH=16 where MACN=4;
update CHINHANH set TRUONGCHINHANH=21 where MACN=5;

/* NV01 -> NV05 thuộc CHINHANH 1*/
/* NV06 -> NV10 thuộc CHINHANH 2*/
/* NV11 -> NV15 thuộc CHINHANH 3*/
/* NV16 -> NV20 thuộc CHINHANH 4*/
/* NV21 -> NV25 thuộc CHINHANH 5*/
/* các CN lần lượt   1, 2,  3,  4, 5     có:*/
/* trưởng chi nhánh  01, 06, 11, 16, 21*/
/* trưởng phòng 	 02, 07, 12, 17, 22*/
/* trưởng dự án 	 03, 08, 13, 18, 23*/
/*
DELETE FROM NHANVIEN;
DELETE FROM CHINHANH;
DELETE FROM PHONGBAN;
DELETE FROM DUAN;
DELETE FROM PHANCONG;
DELETE FROM CHITIEU;

Drop table NHANVIEN;
Drop table CHINHANH;
Drop table PHONGBAN;
Drop table DUAN;
Drop table PHANCONG;
Drop table CHITIEU;

Select * from NHANVIEN;
Select * from CHINHANH;
Select * from PHONGBAN;
Select * from DUAN;
Select * from PHANCONG;
Select * from CHITIEU;
*/