-- kiểm tra đã OLS có sẵn sàng trên DB
select status from dba_ols_status where name = 'OLS_CONFIGURE_STATUS';
select value from v$option where parameter = 'Oracle Label Security';
-- unlock LBACSYS account
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;

--tạo SEC_ADMIN để quan lý chính sách
GRANT connect TO sec_admin IDENTIFIED BY secadmin;
-- login LBACSYS tạo chính sách, 
BEGIN
    SA_SYSDBA.CREATE_POLICY (
    policy_name => 'ACCESS_DUAN',
    column_name => 'OLS_COLUMN_DUAN');
END;
/*
BEGIN
    SA_SYSDBA.DROP_POLICY (
    policy_name => 'ACCESS_DUAN');
END;
*/
-- GÁN QUYỀN THỰC THI CÁC PACKAGE LIÊN QUAN
GRANT ACCESS_DUAN_DBA TO sec_admin;

-- Package dùng để tạo ra các thành phần của nhãn
GRANT execute ON sa_components TO sec_admin;

-- Package dùng để tạo các nhãn
GRANT execute ON sa_label_admin TO sec_admin;

-- Package dùng để gán chính sách cho các table/schema
GRANT execute ON sa_policy_admin TO sec_admin;

-- DÙNG SEC_ADMIN
-- TẠO CÁC GROUP LÀ ĐỊA ĐIỂM RỘNG NHẤT CỦA DỰ ÁN
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_DUAN',1,'TCT','TỔNG CÔNG TY',NULL);
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_DUAN',2,'HCMC','TP HỒ CHÍ MINH','TCT');
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_DUAN',3,'HNC','HÀ NỘI','TCT');
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_DUAN',4,'DNC','ĐÀ NẴNG','TCT');

/* DROP GROUP
EXEC SA_COMPONENTS.DROP_GROUP('ACCESS_DUAN',1);
EXEC SA_COMPONENTS.DROP_GROUP('ACCESS_DUAN',2);
EXEC SA_COMPONENTS.DROP_GROUP('ACCESS_DUAN',3);
EXEC SA_COMPONENTS.DROP_GROUP('ACCESS_DUAN',4);
*/

-- TẠO CÁC COMPARTMENT LÀ PHÒNG CHỦ TRÌ DỰ ÁN
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_DUAN',100,'PNS','NHÂN SỰ');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_DUAN',200,'PKT','KẾ TOÁN');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_DUAN',300,'PKH','KẾ HOẠCH');

/* DROP GROUP
EXEC SA_COMPONENTS.DROP_COMPARTMENT('ACCESS_DUAN',100);
EXEC SA_COMPONENTS.DROP_COMPARTMENT('ACCESS_DUAN',200);
EXEC SA_COMPONENTS.DROP_COMPARTMENT('ACCESS_DUAN',300);
*/

-- TẠO ĐỘ NHẠY CẢM CỦA DỰ ÁN LEVEL
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DUAN',1000,'TT','THÔNG THƯỜNG');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DUAN',2000,'GH','GIỚI HẠN');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DUAN',3000,'BM','BÍ MẬT');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DUAN',4000,'BMC','BÍ MẬT CAO');

/* DROP GROUP
EXEC SA_COMPONENTS.DROP_LEVEL('ACCESS_DUAN',1000);
EXEC SA_COMPONENTS.DROP_LEVEL('ACCESS_DUAN',2000);
EXEC SA_COMPONENTS.DROP_LEVEL('ACCESS_DUAN',3000);
EXEC SA_COMPONENTS.DROP_LEVEL('ACCESS_DUAN',4000);
*/
-- TẠO NHÃN
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 10, 'BMC:PNS:HCMC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 20, 'BMC:PNS:HNC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 30, 'BMC:PNS:DNC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 40, 'BMC:PKT:HCMC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 50, 'BMC:PKT:HNC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 60, 'BMC:PKT:DNC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 70, 'BMC:PKH:HCMC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 80, 'BMC:PKH:HNC');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('ACCESS_DUAN', 90, 'BMC:PKH:DNC');
/* XÓA NHÃN
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 10);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 20);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 30);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 40);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 50);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 60);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 70);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 80);
EXEC SA_LABEL_ADMIN.DROP_LABEL('ACCESS_DUAN', 90);
*/

-- GÁN CHÍNH SÁCH OLS LÊN BẢNG DỰ ÁN 
EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY('ACCESS_DUAN', 'HCMUS', 'DUAN', 'NO_CONTROL');
-- GỠ CHÍNH SÁCH OLS TRÊN BẢN DỰ ÁN
EXEC SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('ACCESS_DUAN', 'HCMUS', 'DUAN');
