-- [X] Chỉ trưởng phòng, trưởng chi nhánh được cấp quyền thực thi stored procedure cập nhật thông tin phòng ban của mình (DAC)
-- tạo procedure

CREATE OR REPLACE PROCEDURE sp_Update_PHONGBAN
(p_MAPHONG IN NUMBER, p_TENPHONG IN VARCHAR2, p_TRUONGPHONG IN NUMBER,
 p_NGAYNHANCHUC IN DATE, p_SONHANVIEN IN NUMBER, p_CHINHANH IN NUMBER) 
IS USERNAME VARCHAR2(5)
BEGIN
	USERNAME :=sys_context('userenv', 'session_user');
	update HCMUS.PHONGBAN SET HCMUS.PHONGBAN.TENPHONG = p_TENPHONG,
							HCMUS.PHONGBAN.TRUONGPHONG =  p_TRUONGPHONG,
							HCMUS.PHONGBAN.NGAYNHANCHUC = p_NGAYNHANCHUC,
							HCMUS.PHONGBAN.SONHANVIEN = p_SONHANVIEN,
							HCMUS.PHONGBAN.CHINHANH = p_CHINHANH
							where HCMUS.PHONGBAN.MAPHONG = p_MAPHONG
								AND (HCMUS.PHONGBAN.TRUONGPHONG = USERNAME
										OR HCMUS.PHONGBAN.CHINHANH IN 
										(SELECT HCMUS.CHINHANH.MACN FROM HCMUS.CHINHANH 
											WHERE HCMUS.CHINHANH.TRUONGCHINHANH=USERNAME)
									);
END sp_Update_PHONGBAN;

grant execute HCMUS.sp_Update_PHONGBAN to R_TRUONGPHONG;
grant execute HCMUS.sp_Update_PHONGBAN to R_TRUONGCHINHANH;

begin
for TRUONGPB_LIST in (select TRUONGPHONG from HCMUS.PHONGBAN)
loop
  execute immediate 'grant R_TRUONGPHONG to ' || TRUONGPB_LIST.TRUONGPHONG; 
end loop;
end;

begin
for TRUONGCN_LIST in (select TRUONGCHINHANH from HCMUS.CHINHANH)
loop
  execute immediate 'grant R_TRUONGCHINHANH to ' || TRUONGCN_LIST.TRUONGCHINHANH; 
end loop;
end;