/* role: Giám đốc được phép xem thông tin dự án gồm (mã dự án, tên dự án, kinh phí,
 tên phòng chủ trì, tên chi nhánh chủ trì, tên trưởng dự án và tổng chi) (DAC)*/
 /* TẠO VIEW CHO ROLE */
 CREATE VIEW V1_CHITIET_DUAN 
    AS SELECT DUAN.MADA, DUAN.TENDA, DUAN.KINHPHI, PHONGBAN.TENPHONG, CHINHANH.TENCN, NHANVIEN.HOTEN AS TENTRUONGDA
        FROM PHONGBAN, DUAN, CHINHANH, NHANVIEN 
        WHERE PHONGBAN.MAPHONG = DUAN.PHONGCHUTRI 
            AND PHONGBAN.CHINHANH = CHINHANH.MACN
            AND DUAN.TRUONGDA = NHANVIEN.MANV;
 CREATE ROLE GIAMDOC_ROLE;
 GRANT SELECT ON V1_CHITIET_DUAN TO GIAMDOC_ROLE;