-- Giám đốc được phép xem thông tin dự án gồm (mã dự án, tên dự án, kinh phí, 
-- tên phòng chủ trì, tên chi nhánh chủ trì, tên trưởng dự án và tổng chi) (DAC)
-- VIEW ĐỂ GIÁM ĐỐC XEM THÔNG TIN CHI TIẾT DỰ ÁN
CREATE OR REPLACE VIEW V_CHITIET_DUAN AS 
	SELECT HCMUS.DUAN.MADA, HCMUS.DUAN.TENDA, HCMUS.DUAN.KINHPHI, HCMUS.PHONGBAN.TENPHONG, HCMUS.CHINHANH.TENCN, HCMUS.NHANVIEN.HOTEN AS TENTRUONGDA
    FROM HCMUS.PHONGBAN, HCMUS.DUAN, HCMUS.CHINHANH, HCMUS.NHANVIEN 
    WHERE HCMUS.PHONGBAN.MAPHONG = HCMUS.DUAN.PHONGCHUTRI
		AND HCMUS.PHONGBAN.CHINHANH = HCMUS.CHINHANH.MACN
		AND HCMUS.DUAN.TRUONGDA = HCMUS.NHANVIEN.MANV;

grant select on HCMUS.V_CHITIET_DUAN TO R_GIAMDOC;

begin
for GIAMDOC_LIST in (select HCMUS.NHANVIEN.MANV from HCMUS.NHANVIEN WHERE HCMUS.NHANVIEN.CHUCVU = 1)
loop
  execute immediate 'grant R_GIAMDOC to ' || GIAMDOC_LIST.MANV; 
end loop;
end;