CREATE USER HCMUS IDENTIFIED BY HCMUS;
GRANT DBA, RESOURCE TO HCMUS WITH ADMIN OPTION;
GRANT CREATE SESSION TO HCMUS;
GRANT ALL PRIVILEGES TO HCMUS;
GRANT EXEMPT ACCESS POLICY TO HCMUS;


/* tạo bảng nhân viên*/
CREATE TABLE NHANVIEN 
(
  MANV VARCHAR2(5)
, HOTEN VARCHAR2(50) 
, DIACHI VARCHAR2(50) 
, DIENTHOAI VARCHAR2(50) 
, EMAIL VARCHAR2(50) 
, MAPHONG VARCHAR2(5)
, CHINHANH VARCHAR2(5)
, LUONG NUMBER
, CHUCVU NUMBER 
, CONSTRAINT NHANVIEN_PK PRIMARY KEY(MANV)
);
/* tạo bảng phong ban*/
CREATE TABLE PHONGBAN 
(
  MAPHONG VARCHAR2(5)
, TENPHONG VARCHAR2(50) 
, TRUONGPHONG VARCHAR2(5) 
, NGAYNHANCHUC DATE 
, SONHANVIEN NUMBER 
, CHINHANH VARCHAR2(5) 
, CONSTRAINT PHONGBAN_PK PRIMARY KEY(MAPHONG)
);

/* tạo bảng chi nhánh */
CREATE TABLE CHINHANH(
  MACN VARCHAR2(5)
, TENCN VARCHAR2(50)
, TRUONGCHINHANH VARCHAR2(5)
, CONSTRAINT CHINHANH_PK PRIMARY KEY(MACN)
);

/* tạo bảng dự án*/
CREATE TABLE DUAN 
(
  MADA VARCHAR2(5)
, TENDA VARCHAR2(50)
, KINHPHI NUMBER
, PHONGCHUTRI VARCHAR2(5)
, TRUONGDA VARCHAR2(5)
, CONSTRAINT DUAN_PK PRIMARY KEY(MADA) 
);

/* tạo bảng phân công*/
CREATE TABLE PHANCONG 
(
  MANV VARCHAR2(5)
, DUAN VARCHAR2(5)
, VAITRO VARCHAR2(50) 
, PHUCAP NUMBER 
, CONSTRAINT PHANCONG_PK PRIMARY KEY(MANV,DUAN)
);

/* tạo bảng chi tiêu*/
CREATE TABLE CHITIEU 
(
  MACHITIEU VARCHAR2(5) 
, TENCHITIEU VARCHAR2(50)
, SOTIEN NUMBER
, DUAN VARCHAR2(5) 
, CONSTRAINT CHITIEU_PK PRIMARY KEY(MACHITIEU)
);

/* khóa ngoại*/
ALTER TABLE CHINHANH ADD CONSTRAINT FK_CHINHANH_NHANVIEN FOREIGN KEY (TRUONGCHINHANH) REFERENCES NHANVIEN(MANV);
ALTER TABLE CHITIEU ADD CONSTRAINT FK_CHITIEU_DUAN FOREIGN KEY (DUAN) REFERENCES DUAN(MADA);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_DUAN FOREIGN KEY (DUAN) REFERENCES DUAN(MADA);
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PHONGBAN_CHINHANH FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE DUAN ADD CONSTRAINT FK_DUAN_PHONGBAN FOREIGN KEY (PHONGCHUTRI) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE DUAN ADD CONSTRAINT FK_DUAN_NHANVIEN FOREIGN KEY (TRUONGDA) REFERENCES NHANVIEN(MANV);



-- CÁC HÀM PHỤC VỤ CÀI ĐẶT CHÍNH SÁCH VPD
--tạo package SET_NHANVIEN_CTX_PKG
create or replace package SET_NHANVIEN_CTX_PKG
as
    procedure SET_PHONGBAN;
    procedure CHECK_TRUONGPHONG;
    procedure CHECK_TRUONGCHINHANH;
    procedure CHECK_TRUONGDUAN;
	procedure CHECK_GIAMDOC;
end;

--tạo context NHANVIEN_CTX
CREATE OR REPLACE CONTEXT NHANVIEN_CTX USING SET_NHANVIEN_CTX_PKG;
-- nội dung pkg

create or replace package body SET_NHANVIEN_CTX_PKG
as
  procedure SET_PHONGBAN
  as PHONGBAN varchar2(5);
  begin
    select MAPHONG into PHONGBAN from HCMUS.NHANVIEN where MANV = sys_context('userenv', 'session_user');
    dbms_session.set_context('NHANVIEN_CTX', 'PHONGBAN', PHONGBAN);
  end;
  
  procedure CHECK_TRUONGPHONG
  as ISTRUONGPB varchar2(5);
  begin
    select case 
        when exists(select MAPHONG  from HCMUS.PHONGBAN where TRUONGPHONG = sys_context('userenv', 'session_user'))
        then 'TRUE'
        else 'FALSE'
      end into ISTRUONGPB
    from dual;
    dbms_session.set_context('NHANVIEN_CTX', 'ISTRUONGPB', ISTRUONGPB);
  end;
  
  procedure CHECK_TRUONGCHINHANH
  as ISTRUONGCN varchar2(5);
  begin
    select case 
        when exists(select MACN  from HCMUS.CHINHANH where TRUONGCHINHANH = sys_context('userenv', 'session_user'))
        then 'TRUE'
        else 'FALSE'
      end into ISTRUONGCN
    from dual;
    dbms_session.set_context('NHANVIEN_CTX', 'ISTRUONGCN', ISTRUONGCN);
  end;
  
  procedure CHECK_TRUONGDUAN
  as ISTRUONGDA varchar2(5);
  begin
    select case 
        when exists(select MADA  from HCMUS.DUAN where TRUONGDA = sys_context('userenv', 'session_user'))
        then 'TRUE'
        else 'FALSE'
      end into ISTRUONGDA
    from dual;
    dbms_session.set_context('NHANVIEN_CTX', 'ISTRUONGDA', ISTRUONGDA);
  end;
  
  procedure CHECK_GIAMDOC
  as ISGIAMDOC varchar2(5);
  begin
    select case 
        when exists(select MANV  from HCMUS.NHANVIEN where CHUCVU = 1)
        then 'TRUE'
        else 'FALSE'
      end into ISGIAMDOC
    from dual;
    dbms_session.set_context('NHANVIEN_CTX', 'ISGIAMDOC', ISGIAMDOC);
  end;
end;

--tạo logon trigger cho package
create or replace trigger set_NHANVIEN_CTX_TRIGGER after logon on database
begin
    HCMUS.SET_NHANVIEN_CTX_PKG.SET_PHONGBAN;
    HCMUS.SET_NHANVIEN_CTX_PKG.CHECK_TRUONGPHONG;
    HCMUS.SET_NHANVIEN_CTX_PKG.CHECK_TRUONGCHINHANH;
    HCMUS.SET_NHANVIEN_CTX_PKG.CHECK_TRUONGDUAN;
	HCMUS.SET_NHANVIEN_CTX_PKG.CHECK_GIAMDOC;
end;
