/* tạo bảng nhân viên*/
CREATE TABLE NHANVIEN 
(
  MANV NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, HOTEN VARCHAR2(50) 
, DIACHI VARCHAR2(50) 
, DIENTHOAI VARCHAR2(50) 
, EMAIL VARCHAR2(50) 
, MAPHONG NUMBER
, CHINHANH NUMBER
, LUONG NUMBER
, CHUCVU NUMBER 
, CONSTRAINT NHANVIEN_PK PRIMARY KEY 
  (
    MANV
  )
  ENABLE 
);
/* tạo bảng phong ban*/
CREATE TABLE PHONGBAN 
(
  MAPHONG NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, TENPHONG VARCHAR2(50) 
, TRUONGPHONG NUMBER 
, NGAYNHANCHUC DATE 
, SONHANVIEN NUMBER 
, CHINHANH NUMBER 
, CONSTRAINT PHONGBAN_PK PRIMARY KEY 
  (
    MAPHONG 
  )
  ENABLE 
);

/* tạo bảng chi nhánh */
CREATE TABLE CHINHANH(
  MACN NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, TENCN VARCHAR2(50)
, TRUONGCHINHANH NUMBER
, CONSTRAINT CHINHANH_PK PRIMARY KEY 
  (
    MACN 
  )
  ENABLE 
);

/* tạo bảng dự án*/
CREATE TABLE DUAN 
(
  MADA NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) 
, TENDA VARCHAR2(50)
, KINHPHI NUMBER
, PHONGCHUTRI NUMBER
, TRUONGDA NUMBER
, CONSTRAINT DUAN_PK PRIMARY KEY 
  (
    MADA 
  )
  ENABLE 
);

/* tạo bảng phân công*/
CREATE TABLE PHANCONG 
(
  MANV NUMBER
, DUAN NUMBER
, VAITRO VARCHAR2(50) 
, PHUCAP NUMBER 
, CONSTRAINT PHANCONG_PK PRIMARY KEY 
  (
    MANV 
  , DUAN 
  )
  ENABLE 
);

/* tạo bảng chi tiêu*/
CREATE TABLE CHITIEU 
(
  MACHITIEU NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) 
, TENCHITIEU VARCHAR2(50)
, SOTIEN NUMBER
, DUAN NUMBER 
, CONSTRAINT CHITIEU_PK PRIMARY KEY 
  (
    MACHITIEU 
  )
  ENABLE 
);

/* khóa ngoại*/
ALTER TABLE CHINHANH ADD FOREIGN KEY (TRUONGCHINHANH) REFERENCES NHANVIEN(MANV);
ALTER TABLE CHITIEU ADD FOREIGN KEY (DUAN) REFERENCES DUAN(MADA);
ALTER TABLE NHANVIEN ADD FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE NHANVIEN ADD FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE PHANCONG ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE PHANCONG ADD FOREIGN KEY (DUAN) REFERENCES DUAN(MADA);
ALTER TABLE PHONGBAN ADD FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE DUAN ADD FOREIGN KEY (PHONGCHUTRI) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE DUAN ADD FOREIGN KEY (TRUONGDA) REFERENCES NHANVIEN(MANV);