/* tạo bảng nhân viên*/
CREATE TABLE NHANVIEN 
(
  MANV NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, HOTEN VARCHAR2(50) 
, DIACHI VARCHAR2(50) 
, DIENTHOAI VARCHAR2(50) 
, EMAIL VARCHAR2(50) 
, MAPHONG NUMBER
, CHINHANH NUMBER
, LUONG NUMBER
, CHUCVU NUMBER 
, CONSTRAINT NHANVIEN_PK PRIMARY KEY(MANV)
);
/* tạo bảng phong ban*/
CREATE TABLE PHONGBAN 
(
  MAPHONG NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, TENPHONG VARCHAR2(50) 
, TRUONGPHONG NUMBER 
, NGAYNHANCHUC DATE 
, SONHANVIEN NUMBER 
, CHINHANH NUMBER 
, CONSTRAINT PHONGBAN_PK PRIMARY KEY(MAPHONG)
);

/* tạo bảng chi nhánh */
CREATE TABLE CHINHANH(
  MACN NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, TENCN VARCHAR2(50)
, TRUONGCHINHANH NUMBER
, CONSTRAINT CHINHANH_PK PRIMARY KEY(MACN)
);

/* tạo bảng dự án*/
CREATE TABLE DUAN 
(
  MADA NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) 
, TENDA VARCHAR2(50)
, KINHPHI NUMBER
, PHONGCHUTRI NUMBER
, TRUONGDA NUMBER
, CONSTRAINT DUAN_PK PRIMARY KEY(MADA) 
);

/* tạo bảng phân công*/
CREATE TABLE PHANCONG 
(
  MANV NUMBER
, DUAN NUMBER
, VAITRO VARCHAR2(50) 
, PHUCAP NUMBER 
, CONSTRAINT PHANCONG_PK PRIMARY KEY(MANV,DUAN)
);

/* tạo bảng chi tiêu*/
CREATE TABLE CHITIEU 
(
  MACHITIEU NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) 
, TENCHITIEU VARCHAR2(50)
, SOTIEN NUMBER
, DUAN NUMBER 
, CONSTRAINT CHITIEU_PK PRIMARY KEY(MACHITIEU)
);

/* khóa ngoại*/
ALTER TABLE CHINHANH ADD CONSTRAINT FK_CHINHANH_NHANVIEN FOREIGN KEY (TRUONGCHINHANH) REFERENCES NHANVIEN(MANV);
ALTER TABLE CHITIEU ADD CONSTRAINT FK_CHITIEU_DUAN FOREIGN KEY (MADA) REFERENCES DUAN(MADA);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_DUAN FOREIGN KEY (MADA) REFERENCES DUAN(MADA);
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PHONGBAN_CHINHANH FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MACN);
ALTER TABLE DUAN ADD CONSTRAINT FK_DUAN_PHONGBAN FOREIGN KEY (PHONGCHUTRI) REFERENCES PHONGBAN(MAPHONG);
ALTER TABLE DUAN ADD CONSTRAINT FK_DUAN_NHANVIEN FOREIGN KEY (TRUONGDA) REFERENCES NHANVIEN(MANV);

/* TẠO VIEW ĐỂ CÀI CHÍNH SÁCH*/
CREATE OR REPLACE VIEW V_NHANVIEN AS SELECT * FROM HCMUS.NHANVIEN;
CREATE OR REPLACE VIEW V_CHITIEU AS SELECT * FROM HCMUS.CHITIEU;
CREATE OR REPLACE VIEW V_PHANCONG AS SELECT * FROM HCMUS.PHANCONG;
CREATE OR REPLACE VIEW V_PHONGBAN AS SELECT * FROM HCMUS.PHONGBAN;
CREATE OR REPLACE VIEW V_DUAN AS SELECT * FROM HCMUS.DUAN;
CREATE OR REPLACE VIEW V_CHINHANH AS SELECT * FROM HCMUS.CHINHANH;

CREATE OR REPLACE VIEW V_DSTRUONGPHONG AS SELECT HCMUS.PHONGBAN.TRUONGPHONG FROM HCMUS.PHONGBAN;
CREATE OR REPLACE VIEW V_DSTRUONGCHINHANH AS SELECT HCMUS.CHINHANH.TRUONGCHINHANH FROM HCMUS.CHINHANH;
CREATE OR REPLACE VIEW V_DSTRUONGDA AS SELECT HCMUS.DUAN.TRUONGDA FROM HCMUS.DUAN;


